version: 2

sources:
  - name: raw
    database: ECOMMERCE_ANALYTICS
    schema: RAW
    tables:
      - name: EVENTS_RAW

models:
  - name: stg_events_clean
    description: "Cleaned and transformed events data from RAW layer"
    columns:

      - name: EVENT_TIME
        description: "Timestamp of the event"
        tests:
          - not_null

      - name: EVENT_TYPE
        description: "Type of event - view, cart or purchase"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['view', 'cart', 'purchase']

      - name: PRODUCT_ID
        description: "Unique product identifier"
        tests:
          - not_null
             # removed unique test
             # 136 products have 2 legitimate brands
             # e.g. nerf/hasbro, bugatti/bugati typos
             # source data issue, negligible (0.07%)

      - name: USER_ID
        description: "Unique user identifier"
        tests:
          - not_null

      - name: USER_SESSION
        description: "User session identifier - no nulls allowed"
        tests:
          - not_null

      - name: PRICE
        description: "Product price"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"

      - name: BRAND
        description: "Product brand - unknown if missing"
        tests:
          - not_null

      - name: CATEGORY_CODE
        description: "Full category path - unknown if missing"
        tests:
          - not_null

      - name: CATEGORY_L1
        description: "Top level category"
        tests:
          - not_null

      - name: CATEGORY_LEAF
        description: "Most specific category level"
        tests:
          - not_null

      - name: EVENT_DATE
        description: "Date of the event"
        tests:
          - not_null

      - name: EVENT_HOUR
        description: "Hour of the event 0-23"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]

      - name: DAY_NAME
        description: "Name of the day"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

      - name: DAY_OF_WEEK
        description: "Day of week 0=Sun, 6=Sat"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1, 2, 3, 4, 5, 6]

      - name: IS_WEEKEND
        description: "True if Saturday or Sunday"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [true, false]

      - name: EVENT_MONTH
        description: "Month of the event (1-12)"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

      - name: EVENT_QUARTER
        description: "Quarter of the event (1-4)"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4]

      - name: EVENT_YEAR
        description: "Year of the event"
        tests:
          - not_null

      - name: IS_VIEW
        description: "1 if view event, 0 otherwise"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1]

      - name: IS_CART
        description: "1 if cart event, 0 otherwise"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1]

      - name: IS_PURCHASE
        description: "1 if purchase event, 0 otherwise"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [0, 1]